version: 0.34-dev-{build}
# clone_folder: c:\projects\ghdl
init:
  - ps: Write-Host "Initializing virtual machine ..."

install:
  - ps: Write-Host "Installing requirements after reboot ..."
  - ps: dir "c:\"
  - ps: c:\msys64\usr\bin\pacman -V
#  - ps: c:\msys64\usr\bin\pacman -Syuu --noconfirm
  - ps: c:\msys64\usr\bin\pacman -Q
  - ps: c:\msys64\usr\bin\pacman -S mingw-w64-x86_64-gcc-ada --noconfirm
  - ps: c:\msys64\usr\bin\pacman -S mingw-w64-x86_64-llvm35 --noconfirm
  - ps: pwd
  - ps: mkdir build\mingw64-llvm
  - ps: cd build\mingw64-llvm; c:\msys64\usr\bin\bash.exe -c ../../configure --prefix=C:\Tools\GHDL-0.34-dev-mingw64-llvm --with-llvm-config

build: off
