version: 0.34-dev-{build}
# clone_folder: c:\projects\ghdl
#environment:
#  matrix:
#  - COMPILER: msys2
#  - PLATFORM: x64
#  - MSYS2_ARCH: x86_64
#  - MSYS2_DIR: msys64
#  - MSYSTEM: MINGW64
#  - BIT: 64

init:
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;" + $env:PATH

install:
  - ps: .\dist\appveyor.install.ps1
  - ps: .\dist\appveyor.info.ps1

before_build:
  - ps: .\dist\appveyor.configure.ps1

build: off
build_script:
  - ps: .\dist\appveyor.build.ps1

test_script:
  - ps: pwd
  - ps: cd ..\..\dist; c:\msys64\usr\bin\bash.exe -c "pwd;./testsuite.sh"
