version: 0.34-dev-{build}
# clone_folder: c:\projects\ghdl
init:
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: $env:PATH = "C:\msys64\mingw64;" + $env:PATH

install:
  - ps: Write-Host "Installing requirements..."
#  - ps: dir "c:\"
  - ps: Write-Host $env:PATH
  - ps: C:\msys64\usr\bin\pacman -V
#  - ps: C:\msys64\usr\bin\pacman -Syuu --noconfirm
#  - ps: C:\msys64\usr\bin\pacman -Q
  - ps: C:\msys64\usr\bin\pacman -S mingw-w64-x86_64-llvm35 --noconfirm
  - ps: pwd
  - ps: $env:PATH += ";C:\msys64\mingw64"
  - ps: mkdir build\mingw64-llvm | cd; c:\msys64\usr\bin\bash.exe -c "../../configure --prefix=C:\Tools\GHDL-0.34-dev-mingw64-llvm --with-llvm-config"

build: off
