version: 0.34-dev-{build}
# clone_folder: c:\projects\ghdl
#environment:
#  matrix:
#  - COMPILER: msys2
#  - PLATFORM: x64
#  - MSYS2_ARCH: x86_64
#  - MSYS2_DIR: msys64
#  - MSYSTEM: MINGW64
#  - BIT: 64

init:
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;" + $env:PATH

install:
  - ps: Write-Host "Installing dependencies ..."
  - ps: C:\msys64\usr\bin\pacman -V
#  - ps: C:\msys64\usr\bin\pacman -Q
  - ps: $env:PATH = ($env:PATH.Split(";") | % { if (-not $_.Contains("Program Files (x86)")) { $_ } }) -join ";"
  - ps: Write-Host $env:PATH
  - ps: $env:PATH.Split(";") | % { Write-Host $_}
#  - ps: C:\msys64\usr\bin\pacman -S mingw-w64-x86_64-llvm35 --noconfirm
#  - ps: mkdir build\mingw64-llvm | cd
#  - ps: c:\msys64\usr\bin\bash.exe -c "../../configure --prefix=C:\Tools\GHDL-0.34-dev-mingw64-llvm --with-llvm-config"
  - ps: mkdir build\mingw64-mcode | cd
  - ps: c:\msys64\usr\bin\bash.exe -c "../../configure --prefix=C:\Tools\GHDL-0.34-dev-mingw64-mcode"
  - ps: c:\msys64\usr\bin\bash.exe -c "gcc -v"
  - ps: c:\msys64\usr\bin\bash.exe -c "cpp -v"
  - ps: c:\msys64\usr\bin\bash.exe -c "g++ -v"
  - ps: c:\msys64\usr\bin\bash.exe -c "gcc -print-search-dirs"
  - ps: c:\msys64\usr\bin\bash.exe -c "cpp -print-search-dirs"
  - ps: c:\msys64\usr\bin\bash.exe -c "g++ -print-search-dirs"
  - ps: cd ..\..\dist; c:\msys64\usr\bin\bash.exe -c "pwd;./testsuite.sh"

#build_script:
#test_script:

build: off
