version: 0.34-dev-{build}
# clone_folder: c:\projects\ghdl
#environment:
#  matrix:
#  - COMPILER: msys2
#  - PLATFORM: x64
#  - MSYS2_ARCH: x86_64
#  - MSYS2_DIR: msys64
#  - MSYSTEM: MINGW64
#  - BIT: 64

init:
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;" + $env:PATH

install:
  - ps: Write-Host "Installing dependencies ..."
  - ps: C:\msys64\usr\bin\pacman -V
  - ps: C:\msys64\usr\bin\pacman -Q
  - ps: C:\msys64\usr\bin\pacman -S mingw-w64-x86_64-llvm35 --noconfirm
  - ps: mkdir build\mingw64-llvm | cd; c:\msys64\usr\bin\bash.exe -c "../../configure --prefix=C:\Tools\GHDL-0.34-dev-mingw64-llvm --with-llvm-config"
  - ps: make
  - ps: cd ..\..\dist; bash -c 'pwd;./testsuite.sh'

#build_script:
#test_script:

build: off
