version: 0.34-dev-{build}
# clone_folder: c:\projects\ghdl
init:
  - ps: Write-Host "Initializing virtual machine ..."

install:
  - ps: Write-Host "Installing requirements after reboot ..."
  - ps: dir "c:\"
  - ps: c:\msys64\usr\bin\pacman -V
  - ps: c:\msys64\usr\bin\pacman -Q

build: off
